#if !defined(AMT_TERMINAL_ENGINE_KEYS_HPP)
#define AMT_TERMINAL_ENGINE_KEYS_HPP

namespace amt{

    enum class Keyboard_t : unsigned char{
        NONE = 0,               // NULL
        KEY_TAB = 9,            // TAB
        KEY_ENTER = 13,         // ENTER
        KEY_ESC = 27,           // ESC
        KEY_SPACE = 32,         // ' '
        KEY_EXCLAMATION,        // '!'
        KEY_QUOTES,             // '"'
        KEY_HASH,               // '#'
        KEY_DOLLAR,             // '$'
        KEY_PERCENTAGE,         // '%'
        KEY_AMPERSAND,          // '&'
        KEY_SINGLE_QUOTES,      // '''
        KEY_OPEN_PARENTHESE,    // '('
        KEY_CLOSE_PARENTHESE,   // ')'
        KEY_STAR,               // '*'
        KEY_PLUS,               // '+'
        KEY_COMMA,              // ','
        KEY_SUB,                // '-'
        KEY_PERIOD,             // '.'
        KEY_FORWARD_SLASH,      // '/'
        KEY_0,                  // '0'
        KEY_1,                  // '1'
        KEY_2,                  // '2'
        KEY_3,                  // '3'
        KEY_4,                  // '4'
        KEY_5,                  // '5'
        KEY_6,                  // '6'
        KEY_7,                  // '7'
        KEY_8,                  // '8'
        KEY_9,                  // '9'
        KEY_COLON,              // ':'
        KEY_SEMICOLON,          // ';'
        KEY_LESS_THAN,          // '<'
        KEY_EQUAL,              // '='
        KEY_GREATER_THAN,       // '>'
        KEY_QUESTION_MARK,      // '?'
        KEY_AT,                 // '@'
        KEY_A,                  // 'A'
        KEY_B,                  // 'B'
        KEY_C,                  // 'C'
        KEY_D,                  // 'D'
        KEY_E,                  // 'E'
        KEY_F,                  // 'F'
        KEY_G,                  // 'G'
        KEY_H,                  // 'H'
        KEY_I,                  // 'I'
        KEY_J,                  // 'J'
        KEY_K,                  // 'K'
        KEY_L,                  // 'L'
        KEY_M,                  // 'M'
        KEY_N,                  // 'N'
        KEY_O,                  // 'O'
        KEY_P,                  // 'P'
        KEY_Q,                  // 'Q'
        KEY_R,                  // 'R'
        KEY_S,                  // 'S'
        KEY_T,                  // 'T'
        KEY_U,                  // 'U'
        KEY_V,                  // 'V'
        KEY_W,                  // 'W'
        KEY_X,                  // 'X'
        KEY_Y,                  // 'Y'
        KEY_Z,                  // 'Z'
        KEY_OPEN_BRACKET,       // '['
        KEY_BACK_SLASH,         // '\'
        KEY_CLOSE_BRACKET,      // ']'
        KEY_CARET,              // '^'
        KEY_UNDERSCORE,         // '_'
        KEY_BACK_TICK,          // '`'
        KEY_a,                  // 'a'
        KEY_b,                  // 'b'
        KEY_c,                  // 'c'
        KEY_d,                  // 'd'
        KEY_e,                  // 'e'
        KEY_f,                  // 'f'
        KEY_g,                  // 'g'
        KEY_h,                  // 'h'
        KEY_i,                  // 'i'
        KEY_j,                  // 'j'
        KEY_k,                  // 'k'
        KEY_l,                  // 'l'
        KEY_m,                  // 'm'
        KEY_n,                  // 'n'
        KEY_o,                  // 'o'
        KEY_p,                  // 'p'
        KEY_q,                  // 'q'
        KEY_r,                  // 'r'
        KEY_s,                  // 's'
        KEY_t,                  // 't'
        KEY_u,                  // 'u'
        KEY_v,                  // 'v'
        KEY_w,                  // 'w'
        KEY_x,                  // 'x'
        KEY_y,                  // 'y'
        KEY_z,                  // 'z'
        KEY_OPEN_CURLY,         // '{'
        KEY_VERTICAL_BAR,       // '|'
        KEY_CLOSE_CURLY,        // '}'
        KEY_CLOSE_TILDA,        // '~'
        KEY_DEL,                // 'DEL'
        KEY_F1,                 // 'F1'
        KEY_F2,                 // 'F2'
        KEY_F3,                 // 'F3'
        KEY_F4,                 // 'F4'
        KEY_F5,                 // 'F5'
        KEY_F6,                 // 'F6'
        KEY_F7,                 // 'F7'
        KEY_F8,                 // 'F8'
        KEY_F9,                 // 'F9'
        KEY_F10,                // 'F10'
        KEY_F11,                // 'F11'
        KEY_F12,                // 'F12'
        KEY_UP,                 // Up arrow key
        KEY_LEFT,               // Left arrow key
        KEY_RIGHT,              // Right arrow key
        KEY_DOWN,               // Down arrow key
    };

} // namespace amt


#endif // AMT_TERMINAL_ENGINE_KEYS_HPP
